### ISSUE TITLE
Timers never called with uv.run(uv.RUN_ONCE)

### ISSUE THREAD

**Issue by tbastos** [moteus/lua-lluv#18]
Hey, I'm trying to run my event loop interleaved with `uv.run()` like this:
```lua
local function run()
  while step() do
    uv.run(uv.RUN_ONCE)
  end
end
```
But `uv.run(uv.RUN_ONCE)` never calls my callbacks. If I change to `uv.run()` the callbacks are called correctly, but then I cannot call `step()` every loop. Any idea why uv.RUN_ONCE doesn't work?

I could set an idle callback, but then `uv.run()` would never block to wait for IO, which is something I want. All I want is for `step()` to be called after every uv loop, and uv should block. Any idea? Neither `uv.check()` nor `uv.prepare()` worked as I expected.

Thanks for the help!

**Comment by moteus** [comment]
Just tested 
```Lua
local uv = require "lluv"

print(uv._VERSION)
print(uv.version())

uv.timer():start(1000, function()
	print "hello"
end)

uv.timer():start(2000, function()
	print "world"
end)

local i = 0
while uv.run(uv.RUN_ONCE) > 0 do
	i = i + 1
	print(i)
end
```
output is 
```
0.1.3-dev
1.7.5
hello
1
2
world
```

**Comment by tbastos** [comment]
Indeed it works :+1: There was a bug in my code, you code helped me find it... Thanks!
