### ISSUE TITLE
Cannot install for Lua 5.2 on 32-bit ubuntu

### ISSUE THREAD

**Issue by SinisterRectus** [moteus/lua-lluv#19]
Trying to install lluv out of the box using Luarocks on ubuntu 14.04 LTS 32-bit with Lua 5.2.3. Get the following: [lluverror.txt](https://github.com/moteus/lua-lluv/files/186738/lluverror.txt)

**Comment by moteus** [comment]
What version of LibUVyou have.
It does not complain that can not find `uv.h` file but complain that `uv_stat_t`, `uv_errno_t` etc. types not defined.
I test lluv only on LibUV >=1.0.0
I just check headers of LibUV and there no such types in version 0.9.8 and 0.10.0
But it there on 0.11.29.
So may be you can just use new version of libuv. I think it not neccessary install it in system you can just build static library and link with it (I do this on my trevis test)
https://github.com/moteus/lua-lluv/blob/master/.travis/setup_uv.sh
and
https://github.com/moteus/lua-lluv/blob/master/.travis.yml#L38

**Comment by SinisterRectus** [comment]
I haven't explicitly installed libuv. I'm just installing lluv via Luarocks according to https://luarocks.org/modules/moteus/lluv

**Comment by moteus** [comment]
lluv require [libuv win version >= 1.0](https://github.com/moteus/lua-lluv#compatible-with-libuv100)
How to build/install libuv you can checkout on [their page](https://github.com/libuv/libuv#build-instructions). I give you link how I do this on Travis-CI system.

**Comment by SinisterRectus** [comment]
Never investigated this further. I was under the impression that Luarocks would install everything necessary to run lluv. I ended up using luv instead. Thanks for the help.
